global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ai-support-analytics-system'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ai-support-backend'
    scrape_interval: 5s
    metrics_path: '/api/v1/analytics/raw' # Scraping live system telemetry & latency KPIs
    static_configs:
      - targets: ['backend:8000']
